config/routes.rb
DemoBlog::Application.routes.draw do |map|
  
  root :to => "welcome#index"
  
  match "archives" => "welcome#archives", :as => "archives"
  match "about" => "welcome#about", :as => "about"  
  match "contact" => "welcome#contact", :as => "contact"  

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'register', :sign_out => 'logout' } #Has To Be Before Users Resource Below
  
  resources :users
  resources :posts
  resources :comments
  resources :category
  
end

app/models/comment.rb
class Comment < CouchRest::ExtendedDocument
  
  extend ActiveModel::Naming
  extend CouchConfig::DatabaseFromThread

  property :body
  property :status
  property :name
  property :email
  property :website
  property :post_id
  property :temp_post_id
  
  view_by :temp_post_id
  view_by :_id

  timestamps!

  def generate_post_id
    "test"
  end
          
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
    @comment = Comment.new
    authorize! :create, @comment
  end

  def create
    @comment = Comment.new
    authorize! :create, @comment
    create_comment_params
    
    if @comment.save
      redirect_to :back
      flash[:notice] = "Your Comment Has Been Created."
    end
  end

  def destroy
    get_comment_by_id
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to :back
    flash[:notice] = "Your Comment Has Been Deleted."
  end

  private 
 
  def create_comment_params
    comment_params = params["comment"]
    @comment.body = comment_params["body"]
    @comment.name = comment_params["name"]
    @comment.email = comment_params["email"]
    @comment.website = comment_params["website"]
    #@comment.post_id = comment_params[@post.id]
    @comment.temp_post_id = comment_params["temp_post_id"]
  end

  def get_comment_by_id
    @comment = Comment.by__id(:key => params[:id]).first
  end
  
end

app/views/comments/_comment.html.erb
<div class="comment">
<div class="comment-body"><%= comment.body %>
<p><% if can? :update, comment %>
<%= link_to 'Edit', comment_path({:id => comment.id}) %>
<% end %>
<% if can? :destroy, comment %>
<%= link_to 'Delete', comment_path({:id => comment.id}), :confirm => "Are you sure?", :method => :delete %>
<% end %></p>
</div>
<div class="comment-meta">
<ul>
<li><%= comment.created_at.strftime("%B #{@post.created_at.day.ordinalize}, %Y") %></li>
<li><% if comment.website != "" %><a href="<%= comment.website %>" rel="nofollow"><%= comment.name %></a><% else %><%= comment.name %><% end %></li>
</ul>
</div>
</div>

app/views/comments/_empty.html.erb
<p>No Comments Yet! Go ahead and break the ice.  Make the first one.  We will be very thankful!</p>

app/views/comments/_form.html.erb
<div id="comment-form">
<h2 class="comment-form-title">YOUR THOUGHTS PLEASE</h2>
<%= form_for @comment, :as => :comment, :url => { :controller => "comments", :action => "create" } do |f| %> 

<p><%= f.text_field :name %> Name</p>
<p><%= f.text_field :email %> Email</p>
<p><%= f.text_field :website %> Website</p>
<p><%= f.text_area :body, :size => "40x8" %></p>


<p><%= f.text_field :temp_post_id %> Temp Parent ID</p>
<%= f.submit "Submit" %>
<% end %>
</div>

app/views/comments/_links.html.erb
<div id="comment-links">Please <%= link_to "Register", new_user_registration_path, {:rel => "nofollow" } %> or <%= link_to "Login", new_user_session_path, {:rel => "nofollow" } %> To Leave A Comment</div>