config/routes.rb
DemoBlog::Application.routes.draw do |map|
  
  root :to => "welcome#index"
  
  match "archives" => "welcome#archives", :as => "archives"
  match "about" => "welcome#about", :as => "about"  
  match "contact" => "welcome#contact", :as => "contact"  

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'register', :sign_out => 'logout' } #Has To Be Before Users Resource Below
  
  resources :users
  resources :posts
  resources :comments
  resources :category
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  #before_filter :get_all_categories
  #caches_action :index, :expires_in => 5.minutes#, :if => Proc.new { |controller| !controller.params[:no_cache]} #url?no_cache=true :layout => false,  

  def index
    @posts = Post.by_created_at(:limit => "10")
  end

  def about
  end
  
  def contact
  end

  def archives
  end
  
  private
  
  def get_all_categories
    @categories = Category.by_name
  end

end

app/views/welcome/_post.html.erb
<% @category = post.post_category(post) %>

<div class="post">
<h2><%= link_to(truncate(post.title, :length => 50), post_path({:id => post.slug})) %></h2>
<p><span class="category-link"><%= link_to post.category, category_path({:id => @category.slug}) %></span> <span class="category-time"><%= post.created_at.strftime("%B #{post.created_at.day.ordinalize}, %Y") %></span></p>
<%= truncate(post.body, :length => 300 ) %>
</div>

app/views/welcome/about.html.erb
<% @page_title = "About Us" %>

<h1 class="main-title">ABOUT US</h1>

app/views/welcome/archives.html.erb
<% @page_title = "The Archives" %>

<h1 class="main-title">THE ARCHIVES</h1>

app/views/welcome/contact.html.erb
<% @page_title = "Contact Us" %>

<h1 class="main-title">CONTACT US</h1>

app/views/welcome/index.html.erb
<% @page_title = "Title Goes Here" %>

<h1 class="main-title">LATEST BLOG POSTS</h1>

<% @posts.each do |post|%>
  <%= render :partial => 'post', :locals => {:post => post}%>
<% end %>