config/routes.rb
DemoBlog::Application.routes.draw do |map|
  
  root :to => "welcome#index"
  
  match "archives" => "welcome#archives", :as => "archives"
  match "about" => "welcome#about", :as => "about"  
  match "contact" => "welcome#contact", :as => "contact"  

  devise_for :users, :path_names => { :sign_in => 'login', :sign_up => 'register', :sign_out => 'logout' } #Has To Be Before Users Resource Below
  
  resources :users
  resources :posts
  resources :comments
  resources :category
  
end

app/models/post.rb
class Post < CouchRest::ExtendedDocument
  
  extend ActiveModel::Naming
  extend CouchConfig::DatabaseFromThread

  property :slug
  property :title
  property :body
  property :status
  property :user_id
  property :category

	view_by :slug
  view_by :category,
    :map => 
      "function(doc) {
        if ((doc['couchrest-type'] == 'Post') && (doc['status'] == 'Active')) {
          emit(doc['category'], 1);
        }
      }"

  view_by :created_at, :descending => true,
    :map => 
      "function(doc) {
        if ((doc['couchrest-type'] == 'Post') && (doc['status'] == 'Active')) {
          emit(doc['created_at'], null);
        }
      }"

  timestamps!

  before_save :generate_slug_from_title

  def post_category(post)
     Category.by_name(:key => post.category).first 
  end

  def generate_slug_from_title
    if self.new_document?
      self.slug = Post.clean_title(title)
    end
  end

  def self.clean_title(the_slug)
    the_slug.downcase.gsub(/[^a-z0-9]/,'-').squeeze('-').gsub(/^\-|\-$/,'')
  end
            
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :get_post_by_slug, :only => [:show, :edit, :update, :destroy]
  before_filter :get_all_categories, :only => [:show, :edit, :new]

  def show
    authorize! :read, @post
    @category = Category.by_name(:key => @post.category).first
    @comments = Comment.by_temp_post_id(:key => @post.id)
  end

	def new
    @post = Post.new
    authorize! :create, @post
    #@categories = Category.by_name
  end

  def edit
    authorize! :update, @post
    #@categories = Category.by_name
  end

  def update
    authorize! :update, @post
    create_post_params
    @post.save
    redirect_to post_path
    flash[:notice] = 'Your Post Has Been Updated.  Woohoo!'
  end

  def create
    @post = Post.new
    authorize! :create, @post
    create_post_params
    
    if @post.save
      redirect_to post_path({:id => @post.slug})
      flash[:notice] = 'Your Post Has Been Created.'
    end
  end

  def destroy
    authorize! :destroy, @post
    @post.destroy
    redirect_to root_path
    flash[:notice] = 'Your Post Has Been Deleted.'
  end

  private
  
  def create_post_params
    post_params = params["post"]
    @post.title = post_params["title"]
    @post.body = post_params["body"]
	  @post.status = post_params["status"]
    @post.category = post_params["category"]
    @post.user_id = current_user.id
  end
  
  def get_post_by_slug
    @post = Post.by_slug(:key => params[:id]).first
  end

  def get_all_categories
    @categories = Category.by_name
  end

  
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def post_post_path(post)
    if post.new_document?
      posts_path
    else
      post_path({:id => post.slug})
    end
  end
  
end

app/views/posts/_form.html.erb
<% categories = @categories.map { |category| [category.name] } %>

<%= form_for :post, @post, :url => post_post_path(@post) do |f| %>
<b>Title</b>
<p><%= f.text_field :title, :size => "78" %></p>
<b>Body</b>
<p><%= f.text_area :body, :size => "60x30" %></p>
<b>Category</b>
<p><%= f.select(:category, categories) %></p>
<b>Status</b>
<p><%= f.select(:status, ["Active", "Inactive"]) %></p>
<%= f.submit "Save" %>
<% end %>

app/views/posts/edit.html.erb
<% @page_title = "Edit Post" %>

<h1 class="main-title">EDIT POST</h1>

<%= form_for @post, :as => :post, :url => { :controller => "posts", :action => "update" } do |f| %>
<b>Title</b>
<p><%= f.text_field :title, :size => "78" %></p>
<b>Body</b>
<p><%= f.text_area :body, :size => "60x30" %></p>
<b>Status</b>
<p><%= f.select(:status, ["Active", "Inactive"]) %></p>
<%= f.submit "Save" %>
<% end %>

app/views/posts/new.html.erb
<% @page_title = "New Post" %>

<h1>New Post</h1>

<%= render :partial => 'form'%> 

app/views/posts/show.html.erb
<% @page_title = @post.title %>

<div id="post">
<h1 class="main-title"><%= @page_title %></h1>
<p><span class="category-link"><%= link_to @post.category, category_path({:id => @category.slug}) %></span> <span class="category-time"><%= @post.created_at.strftime("%B #{@post.created_at.day.ordinalize}, %Y") %></span></p>
<div class="post_content">
<%= (textilize(@post.body)).html_safe %>
</div>
<p>
<% if can? :update, @post %>
<%= link_to "Edit", edit_post_path({:id => @post.slug}) %>
<% end %>
<% if can? :destroy, @post %>
<%= link_to 'Delete', post_path({:id => @post.slug}), :confirm => "Are you sure?", :method => :delete %>
<% end %>
</p>

<div id="temp-post-id-block">
<p>Post ID: <%= @post.id %></p>
<p>We have to temporarily output the post id above so that we can easily copy and paste it into the comment form below.  Hopefully sometime soon I can figure out how to get the id of the post automatically so I don't have to do this any longer.</p>
</div>

</div><!-- /post -->

<div id="comments">
<h2><% if @comments.count == 1 %><%= @comments.count %> COMMENT<% else %><%= @comments.count %> COMMENTS<% end %></h2>

<% @comments.each do |a| %>
	<%= render :partial => 'comments/comment', :object => a %>
<% end %>

<% if @comments.count == 0 %>
<%= render :partial => 'comments/empty' %>
<% end %>

<%= render :partial => 'comments/form' %>
</div><!-- /comments -->	